---
# based on https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-automate-initial-server-setup-on-ubuntu-18-04
- name: Setup operations user
  hosts: all
  become: true
  vars_files:
    - vars/init_user_vars.yaml

  tasks:
    # Sudo Group Setup
    - name: Make sure we have a 'pcewheel' group
      group:
        name: pcewheel
        gid: 4100
        state: present

    - name: Allow 'pcewheel' group to have passwordless sudo
      copy:
        content: "%pcewheel ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/99-pce-wheel-nopass
        owner: root
        group: root
        mode: 0440
        validate: visudo -cf %s

    # User + Key Setup
    - name: Create primary group for a user
      group:
        name: "{{ create_user }}"
        gid: 4000
        state: present

    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ create_user }}"
        uid: 4000
        state: present
        group: "{{ create_user }}"
        groups: pcewheel
        append: true
        create_home: true
        shell: /bin/bash

    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ create_user }}"
        state: present
        key: "{{ copy_local_key }}"
    
    - name: Disable Root Login
      lineinfile: >
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
      notify:
        - restart ssh
  handlers:
   - name: restart ssh
     service: >
       name=sshd
       state=restarted
