---
# TODO: split per architecture, i.e. ubuntu / centos etc.
- name: Home server infrastructure components
  hosts: all
  roles:
    - role: os_basics
    - role: samba
    - role: ufw
    - role: net_ups_tools
